### ISSUE TITLE
Inconsistent license banners

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-presets#19]
There are two versions of license banners:

```javascript
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */
```

and

```javascript
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see http://ckeditor.com/license
 */
```

It seems that the first version is used only in `presets/<name>-ckeditor-config.js`. As we don't have `LICENSE.md` file in this repo, probably we should stick to the second version.

**Comment by mlewand** [comment]
Actually the link URL should be changed too as it was moved not that long ago. So that it should link to https://ckeditor.com/legal/ckeditor-oss-license
